### ISSUE TITLE
Feature request: save the palette values as search params so you can bookmark the palette.

### ISSUE THREAD

**Issue by JorensM** [edelstone/material-palette-generator#12] opened 2024-04-07 05:29 UTC
I'd like it for the tool to save the selected palette colors as search params and load a palette based on those params if there are any. This would allow one to save any palette as a bookmark for later use. I can also make a PR for this, if this project is still being maintained.

**Comment by edelstone** [comment] 2024-04-07 10:27
Hi @JorensM, I think this is a duplicate of #1. Take a look and feel free to do some work on it. We did something similar a while back on the [Tint and Shade Generator](https://github.com/edelstone/tints-and-shades/pull/7), another project I manage.

**Comment by edelstone** [comment] 2024-04-07 10:29
See #1

**Closed as not planned by edelstone** 2024-04-07 10:29 UTC
Labels: duplicate

**Comment by JorensM** [comment] 2024-04-07 10:31
@edelstone Alright, sorry for the duplicate issue. I'll check out your other project and give a go at making a PR for this feature.

**Comment by edelstone** [comment] 2024-04-07 10:35
No worries, and thank you! I'd love the help.

**Comment by edelstone** [comment] 2024-04-07 10:38
And don't feel constrained by however we did it on the other project. Thanks again!
